### ISSUE TITLE
Bug import species name

### ISSUE THREAD

**Issue by pvictor** [dreamRs/conrappli#11]
Dans le module GBIF, les noms d'espèces sont mal lus dans le copier / coller.
=> problème de parsing  / séparateur

**Comment by gdauby** [comment]
J'ai testé en collant le nom d'une espèce (par exemple `Afrocarpus mannii`) il m'indique ` Ooops File not found: Afrocarpus mannii`
Par contre si je fait un saut de ligne alors ca marche
 `Data ready to be imported! data has 1 obs. of 2 variables.`
D'ailleurs je ne comprends pas pourquoi dil 1 obs et 2 variables.
