### ISSUE TITLE
Error in buildTabset

### ISSUE THREAD

**Issue by gdauby** [dreamRs/conrappli#24]
Quand je lance l'appli en local, l'erreur suivante apparait.

>   96: stop
>   95: buildTabset
>   94: tabsetPanel_
>   93: navs_pill
>   90: bslib::navs_pill_card
>   84: summary_report_ui [D:/MonDossierR/conrappli_dreams/R/module-report.R#20]
>   69: ui [D:/MonDossierR/conrappli_dreams/R/conr-ui.R#16]

Quand la ligne `title = "Report",` de la fonction `bslib::navs_pill_card` du module `module-report.R` est supprimé ça fonctionne.

@pvictor

**Comment by pvictor** [comment]
Cet argument existe bien dans la dernière version de bslib sur le CRAN, je rajouterai une condition sur le numéro de version.
