### ISSUE TITLE
Erreur dans le deploiement de l'appli

### ISSUE THREAD

**Issue by gdauby** [dreamRs/conrappli#26]
Je tente de déployer l'appli dans mon serveur shinyapps.io mais j'observe une erreur lors du 'Deploy' :

> Application successfully deployed to https://gdauby.shinyapps.io/conapp/
> Deployment completed: https://gdauby.shinyapps.io/conapp/
> Message d'avis :
> Error detecting locale: Error in read.table(file = file, header = header, sep = sep, quote = quote, : ligne finale incomplète trouvée par readTableHeader dans 'raw'
>  (Using default: en_US) 

Le lien fonctionne mais l'appli plante dés qu'on arrive au module criterion_b semble t il, sans message d'erreur spécifique...

Une idée ?

@pvictor

**Comment by pvictor** [comment]
Tu peux ignorer l'erreur sur la détection du locale, ce n'est pas impactant.

L'appli plante avec quelle type de données en entrée ? en local également ?

**Comment by gdauby** [comment]
Non ça ne plante pas en local.

Je vois ce message dans le log

> Container event from container-8068295: oom (out of memory)

Je suppose que la ram de mon serveur gratuit shinyapps.io n'est pas suffisant...

**Comment by pvictor** [comment]
Oui un problème de RAM... Sur mon serveur l'application est paramétré avec "Instance Size: 2X-Large (4 GB)"
