### ISSUE TITLE
Mapping 

### ISSUE THREAD

**Issue by gdauby** [dreamRs/conrappli#31]
Selon la taille de l'écran, le `fluidrow `remove et le `uiOutput `filter_year ne sont pas visibles (dans le module-mapping).

Peut etre faut  il modifier les paramètres de largeur hauteur des différents compartiments ?

Voir la capture d'écran ci dessous

Sur un écran plus grand, ça passe sans problème.

![Image1](https://github.com/dreamRs/conrappli/assets/7722785/e8f63db8-fed0-4722-b77e-6a1e9b504aa0)

**Comment by pvictor** [comment]
J'ai modifié, cela devrait être mieux. J'ai ajouté la possibilité de les déplacer au cas où.

**Comment by gdauby** [comment]
super, je vais regarder. Cela dit je viens de regarder sur la version en ligne et il n'y a pas ce problème, c'est seulement en local apparemment.
