### ISSUE TITLE
traduction sur l'appli en ligne

### ISSUE THREAD

**Issue by gdauby** [dreamRs/conrappli#32]
Salut @pvictor 

La traduction fonctionne bien en local mais ne se déclenche pas sur l'appli en ligne. 

https://gdauby.shinyapps.io/conapp/

Rien n'apparait sur le log.

Une idée pourquoi ?

**Comment by pvictor** [comment]
ça doit dépendre de la façon dont tu déploie, il faut que le package soit installé, pas chargé via `pkgload::load_all()` ou autre.
Je vais regarder.

**Comment by gdauby** [comment]
Je déploie via le raccourci Rstudio à partir du fichier app.R, mais peut etre y a t il une alternative.

```
library(pkgload)
library(shiny)
pkgload::load_all()
options(shiny.autoload.r = FALSE)
shiny::shinyApp(
  ui = conr_ui(),
  server = conr_server()
)
```

**Comment by pvictor** [comment]
Ok, il faut déployer en ayant installé le package explicitement depuis GitHub pour que cela fonctionne, j'utilise ce script : https://github.com/dreamRs/conrappli/blob/master/deploy/app.R
Version en ligne : https://dreamrs.shinyapps.io/conrapp-dev/

**Comment by gdauby** [comment]
super ça semble fonctionner.
