### ISSUE TITLE
plus carte leaflet qui s'affiche

### ISSUE THREAD

**Issue by gdauby** [dreamRs/conrappli#34]
@pvictor 
Depuis hier il me semble le rendu leaflet du module 1 et 3 ne s'affiche plus. C'est un rectangle gris sans carte.
Une idée de ce qu'il se passe ?

La carte du module mapping s'affiche encore.

Ce n'est pas lié au changement de theme de l'appli.

**Comment by pvictor** [comment]
C'est corrigé!
